//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBTASK
    {
        public decimal ID { get; set; }
        public decimal TASK_ID { get; set; }
        public string NAME { get; set; }
        public string ACTION { get; set; }
        public string PARAM { get; set; }
        public decimal TABLE_ID { get; set; }
    
        public virtual TASK TASK { get; set; }
        public virtual TABLE_ACCESS TABLE_ACCESS { get; set; }
    }
}
