//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_ACCESS
    {
        public TABLE_ACCESS()
        {
            this.SUBTASKS = new HashSet<SUBTASK>();
        }
    
        public string TABLE_NAME { get; set; }
        public Nullable<short> IS_FREE { get; set; }
        public string DT { get; set; }
        public string USER_NAME { get; set; }
        public decimal ID { get; set; }
    
        public virtual ICollection<SUBTASK> SUBTASKS { get; set; }
    }
}
